apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gatekeeper-system

commonLabels:
  app: gatekeeper-audit-dashboard

resources:
- deployment.yaml
- cluster-role-binding.yaml
- cluster-role.yaml
- service.yaml
- serviceaccount.yaml

configMapGenerator:
  - name: nginx.conf
    files:
      - nginx.conf
  - name: dashboardconfig
    files:
      - config.cfg=appconfig.cfg